# In this notebook i want to figure out how i can use openCV's camera matrices to represent warping and unwarping

In [8]:
#imports
import numpy as np
import cv2
from warp import *

In [4]:
#some hard-coded image parameters that will later be read from a metadata file
n = 1344 # width in pixels
m = 1004 # height in pixels
n_layers = 35 # number of layers

In [5]:
#initialize a camera matrix 
# all units in pixels
fx = 1. # x focal length
fy = 1. # y focal length
cx = 584 # center principal point x coordinate
#cx = n/2.
cy = 600 # center principal point y coordinate
#cy = m/2.
init_cam_mtx = np.array([[fx,0.,cx],[0.,fy,cy],[0.,0.,1.]])
print(f"init_cam_mtx:\n{init_cam_mtx}\n")

init_cam_mtx:
[[  1.   0. 672.]
 [  0.   1. 502.]
 [  0.   0.   1.]]



In [6]:
#initialize a vector of distortion parameters 
#radial distortion by third-order polynomial in r^2 (numerator)
k1 = 0.
k2 = 0.
k3 = 0.
#tangential distortion
p1 = 0.
p2 = 0.
#radial distortion by third-order polynomial in r^2 (denominator)
k4 = 0.
k5 = 0.
k6 = 0.

init_dist = np.array([k1,k2,p1,p2,k3,k4,k5,k6])
print(f"init_dist:\n{init_dist}\n")

init_dist:
[0. 0. 0. 0. 0. 0. 0. 0.]

